// Shared OrbitFS widget logic - tabs, file browser, vent/journal, server status.
// Host-agnostic: talks only to window.OrbitFSBridge, never to window.openai or
// the ExtApps App class directly. See bridge.chatgpt.js / bridge.claude.js for
// the per-host implementations that get concatenated ahead of this file.

// Fallback bridge so this file never throws if no host bridge claimed the
// interface (e.g. a plain browser tab or an MCP client without apps support).
if (!window.OrbitFSBridge) {
  window.OrbitFSBridge = {
    hostName: "none",
    ready: Promise.resolve(),
    async callTool() { throw new Error("This host does not support OrbitFS widget tools."); },
    async sendChatPrompt() { throw new Error("This host does not support chat follow-ups."); },
    async requestClose() {},
    getInitialView() { return null; },
    onViewUpdate() {},
  };
}

document.documentElement.classList.toggle("claude-host", OrbitFSBridge.hostName !== "chatgpt");
// window.ORBITFS_MCP_ROLE is inlined per-connection by the server (see
// injectMcpRole in server.js) - "member" sessions only have tools for
// Context/Files/Server Status, so Startup/Vent/Journal (which need tools
// that were never registered for them - see MEMBER_ALLOWED_TOOLS) are
// hidden rather than shown broken.
const ORBITFS_RESTRICTED = window.ORBITFS_MCP_ROLE === "member";
document.documentElement.classList.toggle("orbitfs-restricted", ORBITFS_RESTRICTED);

const PANEL_CLAIM_KEY="orbitfs.chatgpt.activePanel";
const PANEL_INSTANCE_ID=`${Date.now()}-${Math.random().toString(36).slice(2)}`;
function hideStalePanel(){const shell=document.querySelector('.shell');if(shell)shell.classList.add('hidden');if(window.closedNote){closedNote.textContent='OrbitFS UI moved to the newest panel.';closedNote.classList.add('show')}}
function claimActivePanel(){try{localStorage.setItem(PANEL_CLAIM_KEY,PANEL_INSTANCE_ID)}catch{}}
window.addEventListener('storage',e=>{if(e.key===PANEL_CLAIM_KEY&&e.newValue&&e.newValue!==PANEL_INSTANCE_ID)hideStalePanel()});
claimActivePanel();

let currentPath='',currentEntries=[],contextPath='',contextEntries=[],selectedProject='',selectedStrength='medium';
function callTool(name,args={}){return OrbitFSBridge.callTool(name,args)}
function textFrom(r){return(r?.content||[]).map(x=>x.text||'').join('\n')}
async function tool(name,args={}){document.querySelector('.shell').classList.add('busy');try{return await callTool(name,args)}finally{document.querySelector('.shell').classList.remove('busy')}}
function selectedValues(select){return[...select.selectedOptions].map(o=>o.value).filter(Boolean)}function parentPath(v){return v.split('/').filter(Boolean).slice(0,-1).join('/')}
let uiMinimized=false;
minimizeUi.onclick=()=>{uiMinimized=!uiMinimized;document.querySelector('.shell').classList.toggle('minimized',uiMinimized);minimizeUi.textContent=uiMinimized?'□':'−';minimizeUi.title=uiMinimized?'Restore':'Minimize'};
closeUi.onclick=async()=>{try{await callTool('orbitfs_ui',{action:'close'})}catch{}const shell=document.querySelector('.shell');shell.classList.add('hidden');closedNote.classList.add('show');try{await OrbitFSBridge.requestClose()}catch{}};
function setTab(name){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===name));if(name==='files')loadFolder(currentPath);if(name==='context'){refreshContextData();loadContextFolder(contextPath)};if(name==='system')refreshServerStatus();if(name==='journal')refreshJournalStatus();if(name==='vent')refreshVentStatus()}
function showMessage(t){fileMessage.textContent=t;fileMessage.classList.remove('hidden')}function setStrength(t,on=true){strength.classList.toggle('on',on);strength.querySelector('span').textContent=t}
document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>{selectedProject=b.dataset.project;document.querySelectorAll('[data-project]').forEach(x=>x.classList.toggle('selected',x===b))});document.querySelectorAll('[data-strength]').forEach(b=>b.onclick=()=>{selectedStrength=b.dataset.strength;document.querySelectorAll('[data-strength]').forEach(x=>x.classList.toggle('selected',x===b))});document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
function parseList(text){return text.split('\n').map(line=>{const m=line.match(/^\[(DIR|FILE)\]\s*(.+)$/);return m?{type:m[1]==='DIR'?'dir':'file',path:m[2].trim()}:null}).filter(Boolean)}
function fillFolderChoices(entries){const folders=entries.filter(e=>e.type==='dir'),opts=[{value:'',label:'OrbitFS root'}];if(currentPath)opts.push({value:parentPath(currentPath),label:'.. Parent folder'});opts.push(...folders.map(f=>({value:f.path,label:f.path.split('/').pop()})));for(const s of[folderChoice,destinationChoice]){s.innerHTML='';for(const i of opts){const o=document.createElement('option');o.value=i.value;o.textContent=i.label;s.appendChild(o)}}}
async function loadFolder(v=''){currentPath=v||'';currentFolder.textContent=currentPath?`/${currentPath}`:'/';itemSelect.innerHTML='<option>Loading…</option>';filePreview.classList.add('hidden');try{const r=await tool('list_files',{subpath:currentPath,recursive:false});currentEntries=parseList(textFrom(r));itemSelect.innerHTML='';for(const e of currentEntries){const o=document.createElement('option');o.value=e.path;o.textContent=`${e.type==='dir'?'📁':'📄'} ${e.path.split('/').pop()}`;o.dataset.type=e.type;itemSelect.appendChild(o)}if(!currentEntries.length)itemSelect.innerHTML='<option disabled>(empty)</option>';fillFolderChoices(currentEntries)}catch(e){itemSelect.innerHTML=`<option disabled>${e.message||e}</option>`}}
function showContextMessage(t){contextMessage.textContent=t;contextMessage.classList.remove('hidden')}
function renderContextEntries(){const q=contextSearch.value.trim().toLowerCase();contextBrowser.innerHTML='';const filtered=contextEntries.filter(e=>!q||e.path.toLowerCase().includes(q));for(const e of filtered){const o=document.createElement('option');o.value=e.path;o.textContent=`${e.type==='dir'?'📁':'📄'} ${e.path.split('/').pop()}`;o.dataset.type=e.type;contextBrowser.appendChild(o)}if(!filtered.length)contextBrowser.innerHTML='<option disabled>(no matches)</option>'}
async function loadContextFolder(v=''){contextPath=v||'';contextFolderPath.textContent=contextPath?`/${contextPath}`:'/';contextBrowser.innerHTML='<option>Loading…</option>';try{const r=await callTool('list_files',{subpath:contextPath,recursive:false});contextEntries=parseList(textFrom(r));renderContextEntries()}catch(e){contextBrowser.innerHTML=`<option disabled>${e.message||e}</option>`}}
contextSearch.oninput=renderContextEntries;contextUp.onclick=()=>loadContextFolder(parentPath(contextPath));contextOpen.onclick=()=>{const o=contextBrowser.selectedOptions[0];if(!o)return;const e=contextEntries.find(x=>x.path===o.value);if(e?.type==='dir')loadContextFolder(e.path);else showContextMessage('Select a folder to open.')};contextBrowser.ondblclick=()=>{const o=contextBrowser.selectedOptions[0];const e=contextEntries.find(x=>x.path===o?.value);if(e?.type==='dir')loadContextFolder(e.path)};contextLoadSelected.onclick=async()=>{const selected=[...contextBrowser.selectedOptions].map(o=>contextEntries.find(e=>e.path===o.value)).filter(e=>e?.type==='file');if(!selected.length)return showContextMessage('Select one or more files.');let loaded=0;for(const e of selected){try{await callTool('load_file',{filepath:e.path});loaded++}catch(err){showContextMessage(`${e.path}: ${err.message||err}`)}}await refreshContextData();showContextMessage(`Loaded ${loaded} file${loaded===1?'':'s'} into context.`)};
function shortNumber(n){const v=Number(n||0);return v>=1000000?`${(v/1000000).toFixed(v>=10000000?0:1)}m`:v>=1000?`${Math.round(v/1000)}k`:String(v)}
function contextStatusLabel(file){const status=file.status||(file.truncated?'partially_loaded':'fully_loaded');return status.replace(/_/g,' ')}
function contextCoverageLabel(file){const loaded=Number(file.charactersLoaded??file.characters??0),total=Number(file.totalCharacters??file.characters??0),coverage=Number(file.coveragePercent??(total?Math.round((loaded/total)*100):100));return `${coverage}% · ${shortNumber(loaded)}/${shortNumber(total)} chars`}
function renderContextManifest(files,d){if(!window.contextManifest)return;const total=d.totalCharactersAvailable??d.totalCharactersLoaded??0;contextManifest.innerHTML=`<div class="context-load-grid"><span><strong>${d.fullyLoadedCount??files.filter(f=>(f.status||'fully_loaded')==='fully_loaded'&&!f.truncated).length}</strong><small>Full</small></span><span><strong>${d.partiallyLoadedCount??files.filter(f=>f.status==='partially_loaded'||f.truncated).length}</strong><small>Partial</small></span><span><strong>${d.referenceOnlyCount??0}</strong><small>Refs</small></span><span><strong>${d.failedCount??0}</strong><small>Failed</small></span></div><div class="context-load-note">Loaded ${shortNumber(d.totalCharactersLoaded||0)} of ${shortNumber(total)} readable chars</div>`}
async function refreshContextData(){try{const r=await callTool('list_active_context',{}),d=r.structuredContent||{},files=d.activeFiles||d.visibleLoadedFiles||[];setStrength((d.loadstrength||selectedStrength||'Active').toUpperCase(),files.length>0);stats.innerHTML=`<span class="pill">${d.activeFileCount??files.length} active</span><span class="pill">${shortNumber(d.totalCharactersLoaded||0)} loaded</span><span class="pill">${d.fullyLoadedCount??0} full</span><span class="pill">${d.partiallyLoadedCount??0} partial</span>`;renderContextManifest(files,d);activeSelect.innerHTML='';for(const f of files){const o=document.createElement('option');o.value=f.path;o.textContent=`${contextStatusLabel(f)} · ${contextCoverageLabel(f)} · ${f.path}`;if(f.warnings?.length)o.textContent+=` · ⚠ ${f.warnings.join('; ')}`;o.dataset.status=f.status||'';o.dataset.coverage=f.coveragePercent??'';activeSelect.appendChild(o)}if(!files.length){activeSelect.innerHTML='<option disabled>No active OrbitFS files</option>';if(window.contextManifest)contextManifest.innerHTML='<div class="context-load-note">No active files loaded.</div>'}return d}catch{return null}}
function showStartupMessage(t){startupMessage.textContent=t;startupMessage.classList.remove('hidden')}
function startupPrompt(args){const mode=args.mega?'MEGA startup':`${args.loadstrength} startup`;return `Read and understand the OrbitFS ${mode} context for ${args.project}. Call startup with project ${JSON.stringify(args.project)}, loadstrength ${JSON.stringify(args.loadstrength)}, mega ${args.mega?'true':'false'}, selectedFiles [], and uiSelectionConfirmed true so the actual file contents are loaded into this chat. After reading it, give me a short confirmation of what context is active and any obvious loading issues.`}
async function runStartup(args){start.disabled=true;mega.disabled=true;showStartupMessage('Loading startup files into OrbitFS...');try{await tool('startup',args);showStartupMessage('Files loaded. Sending read request to ChatGPT...');const d=await refreshContextData();setStrength(args.mega?'MEGA':(d?.loadstrength||args.loadstrength||'Active').toUpperCase(),(d?.activeFileCount||0)>0);await sendChatPrompt(startupPrompt(args));showStartupMessage('Startup loaded. ChatGPT read request sent.');setTab('context')}catch(e){showStartupMessage(e.message||String(e))}finally{start.disabled=false;mega.disabled=false}}
start.onclick=()=>{if(!selectedProject)return alert('Select Legal or Wellbeing.');runStartup({project:selectedProject,loadstrength:selectedStrength,selectedFiles:[],uiSelectionConfirmed:true})};mega.onclick=()=>{if(!selectedProject)return alert('Select Legal or Wellbeing.');if(!askConfirm('Run MEGA?'))return;runStartup({project:selectedProject,loadstrength:'high',mega:true,selectedFiles:[],uiSelectionConfirmed:true})};
function askConfirm(message){return typeof confirm==='function'?confirm(message):true}
loadContextFile.onclick=async()=>{const filepath=contextLoadPath.value.trim();if(!filepath)return;try{await tool('load_file',{filepath});contextLoadPath.value='';await refreshContextData();showContextMessage('Loaded file into context.')}catch(e){showContextMessage(e.message||String(e))}};refreshContext.onclick=refreshContextData;unloadSelected.onclick=async()=>{const filepaths=selectedValues(activeSelect);if(!filepaths.length)return showContextMessage('Select one or more active files.');try{await tool('unload_context_files',{filepaths});await refreshContextData();showContextMessage(`Unloaded ${filepaths.length} file${filepaths.length===1?'':'s'}.`)}catch(e){showContextMessage(e.message||String(e))}};clearContext.onclick=async()=>{try{showContextMessage('Clearing context...');await tool('clear_active_context',{});await refreshContextData();showContextMessage('Cleared all active context.')}catch(e){showContextMessage(e.message||String(e))}};
clearAllContext.onclick=async()=>{try{showContextMessage('Clearing all context...');await tool('clear_all_context',{});await refreshContextData();showContextMessage('Cleared all active context.')}catch(e){showContextMessage(e.message||String(e))}};
openFolder.onclick=()=>loadFolder(folderChoice.value);refreshFiles.onclick=()=>loadFolder(currentPath);itemSelect.ondblclick=()=>{const o=itemSelect.selectedOptions[0];if(o?.dataset.type==='dir')loadFolder(o.value)};previewSelected.onclick=async()=>{const p=selectedValues(itemSelect);if(p.length!==1)return showMessage('Select exactly one file.');const e=currentEntries.find(x=>x.path===p[0]);if(e?.type==='dir')return loadFolder(e.path);const r=await tool('preview_file',{filepath:p[0]});filePreview.textContent=(r.structuredContent?.document?.text||textFrom(r)||'(no preview)').slice(0,3500);filePreview.classList.remove('hidden')};moveSelected.onclick=async()=>{const p=selectedValues(itemSelect);if(!p.length)return showMessage('Select one or more items.');for(const source of p)await tool('move_item',{source,destination_folder:destinationChoice.value,confirmed:true});showMessage('Moved.');loadFolder(currentPath)};trashSelected.onclick=async()=>{const p=selectedValues(itemSelect);if(!p.length||!confirm('Move selected items to trash?'))return;for(const filepath of p)await tool('move_to_trash',{filepath});showMessage('Moved to trash.');loadFolder(currentPath)};renameSelected.onclick=async()=>{const p=selectedValues(itemSelect),n=renameName.value.trim();if(p.length!==1||!n)return showMessage('Select one item and enter a new name.');await tool('move_item',{source:p[0],destination_folder:currentPath,new_name:n,confirmed:true});renameName.value='';loadFolder(currentPath)};
let ventStateData={},journalStateData={};
function showVent(t){ventOutput.textContent=t;ventOutput.classList.remove('hidden')}
function setVentUi(d={}){ventStateData=d;ventState.textContent=d.recording?'RECORDING':d.stopped?'STOPPED':d.enabled?'ON':'OFF';ventState.classList.toggle('on',!!d.enabled);ventDraftState.textContent=d.pendingDraft?'Draft saved':'No draft';startVent.disabled=!d.enabled||d.recording;stopVent.disabled=!d.recording;saveVentDraft.disabled=!d.stopped;reloadVentDraft.disabled=!d.pendingDraft;approveVent.disabled=!d.pendingDraft;deleteVentDraft.disabled=!d.pendingDraft}
async function refreshVentStatus(){try{const r=await callTool('vent_status',{});setVentUi(r.structuredContent||JSON.parse(textFrom(r)||'{}'))}catch{}}
async function sendChatPrompt(prompt){return OrbitFSBridge.sendChatPrompt(prompt)}
onVent.onclick=async()=>{try{const r=await tool('ventmode',{state:'on'});showVent(textFrom(r));await refreshVentStatus()}catch(e){showVent(e.message||String(e))}};
startVent.onclick=async()=>{try{const r=await tool('start_vent_recording',{});showVent(textFrom(r));await refreshVentStatus()}catch(e){showVent(e.message||String(e))}};
stopVent.onclick=async()=>{try{const r=await tool('stop_vent_recording',{});showVent(textFrom(r));await refreshVentStatus()}catch(e){showVent(e.message||String(e))}};
saveVentDraft.onclick=async()=>{try{await sendChatPrompt('Save everything I said since Vent recording started as a Pure Private Vent draft. Preserve it as-is except title, date and paragraph spacing. Call save_vent_draft with the complete text. Do not upload it.');showVent('Draft save request sent to chat.')}catch(e){showVent(e.message||String(e))}};
reloadVentDraft.onclick=async()=>{try{const r=await tool('reload_vent_draft',{});showVent(textFrom(r));await refreshVentStatus()}catch(e){showVent(e.message||String(e))}};
approveVent.onclick=async()=>{try{const r=await tool('upload_vent_entry',{});showVent(textFrom(r));await refreshVentStatus()}catch(e){showVent(e.message||String(e))}};
deleteVentDraft.onclick=async()=>{if(!confirm('Delete saved Vent draft?'))return;try{const r=await tool('delete_vent_draft',{});showVent(textFrom(r));await refreshVentStatus()}catch(e){showVent(e.message||String(e))}};
offVent.onclick=async()=>{try{const r=await tool('ventmode',{state:'off'});showVent(textFrom(r));await refreshVentStatus()}catch(e){showVent(e.message||String(e))}};
function showJournal(t){journalOutput.textContent=t;journalOutput.classList.remove('hidden')}
function setJournalUi(d={}){journalStateData=d;journalState.textContent=d.recording?'RECORDING':d.stopped?'STOPPED':d.enabled?'ON':'OFF';journalState.classList.toggle('on',!!d.enabled);journalDraftState.textContent=d.pendingDraft?'Draft saved':'No draft';startJournal.disabled=!d.enabled||d.recording;stopJournal.disabled=!d.recording;saveJournalDraft.disabled=!d.stopped;reloadJournalDraft.disabled=!d.pendingDraft;approveJournal.disabled=!d.pendingDraft;deleteJournalDraft.disabled=!d.pendingDraft}
async function refreshJournalStatus(){try{const r=await callTool('journal_status',{});setJournalUi(r.structuredContent||JSON.parse(textFrom(r)||'{}'))}catch{}}
onJournal.onclick=async()=>{try{const r=await tool('journalmode',{state:'on'});showJournal(textFrom(r));await refreshJournalStatus()}catch(e){showJournal(e.message||String(e))}};
startJournal.onclick=async()=>{try{const r=await tool('start_journal_recording',{});showJournal(textFrom(r));await refreshJournalStatus()}catch(e){showJournal(e.message||String(e))}};
stopJournal.onclick=async()=>{try{const r=await tool('stop_journal_recording',{});showJournal(textFrom(r));await refreshJournalStatus()}catch(e){showJournal(e.message||String(e))}};
saveJournalDraft.onclick=async()=>{try{await sendChatPrompt('Save everything I said since Journal recording started as a Semi Personal journal draft. Preserve my meaning and wording with only light cleanup for transcription, paragraphs, title and date. Call save_journal_draft with the complete text. Do not upload it.');showJournal('Draft save request sent to chat.')}catch(e){showJournal(e.message||String(e))}};
reloadJournalDraft.onclick=async()=>{try{const r=await tool('reload_journal_draft',{});showJournal(textFrom(r));await refreshJournalStatus()}catch(e){showJournal(e.message||String(e))}};
approveJournal.onclick=async()=>{try{const r=await tool('upload_journal_entry',{});showJournal(textFrom(r));await refreshJournalStatus()}catch(e){showJournal(e.message||String(e))}};
deleteJournalDraft.onclick=async()=>{if(!confirm('Delete saved Journal draft?'))return;try{const r=await tool('delete_journal_draft',{});showJournal(textFrom(r));await refreshJournalStatus()}catch(e){showJournal(e.message||String(e))}};
offJournal.onclick=async()=>{try{const r=await tool('journalmode',{state:'off'});showJournal(textFrom(r));await refreshJournalStatus()}catch(e){showJournal(e.message||String(e))}};
function setService(cardId,textId,online,label){const c=document.getElementById(cardId),t=document.getElementById(textId);c.classList.toggle('online',online);c.classList.toggle('offline',!online);t.textContent=label}
async function refreshServerStatus(){try{const r=await tool('server_status',{}),text=textFrom(r);const hiveRunning=/The OrbitFS Server[\s\S]*?Running:\s*Yes/i.test(text),cloudOnline=/Connected Online:\s*(Likely yes|Yes)/i.test(text)||/The OrbitFS Server[\s\S]*?Online:\s*(Likely yes|Local only)/i.test(text),panelOnline=/Connected locally:\s*Yes/i.test(text),sorterMatch=text.match(/Sorter[^:\n]*:\s*([^\n]+)/i);setService('cardMcp','statusMcp',hiveRunning,hiveRunning?'Online':'Offline');setService('cardCloud','statusCloud',cloudOnline,cloudOnline?'Online':'Offline');setService('cardPanel','statusPanel',panelOnline,panelOnline?'Online':'Offline');const sorterOnline=!!sorterMatch&&!/offline|stopped|missing|not/i.test(sorterMatch[1]);setService('cardSorter','statusSorter',sorterOnline,sorterOnline?'Online':'When will this ever come 🤔');statusOutput.textContent='Checked now';statusOutput.classList.remove('hidden')}catch(e){setService('cardMcp','statusMcp',false,'Offline');setService('cardCloud','statusCloud',false,'Offline');setService('cardPanel','statusPanel',false,'Offline');setService('cardSorter','statusSorter',false,'When will this ever come 🤔');statusOutput.textContent=e.message||String(e);statusOutput.classList.remove('hidden')}}serverStatus.onclick=refreshServerStatus;

let initialViewApplied=false;
function applyInitialView(view){if(initialViewApplied)return;const requested=view||(ORBITFS_RESTRICTED?'context':'startup');const mapped=requested==='browser'?'files':requested;const allowed=ORBITFS_RESTRICTED?['context','files','system']:['startup','context','files','vent','journal','system'];if(allowed.includes(mapped))setTab(mapped);else if(ORBITFS_RESTRICTED)setTab('context');initialViewApplied=true}
OrbitFSBridge.onViewUpdate(applyInitialView);
OrbitFSBridge.ready.then(()=>applyInitialView(OrbitFSBridge.getInitialView()));
setTimeout(()=>applyInitialView(OrbitFSBridge.getInitialView()),0);
refreshContextData();refreshVentStatus();refreshJournalStatus();
